[workspace]
authors = ["Jack Fowler <sxw2830893287@gmail.com>"]
channels = ["conda-forge"]
name = "machine-learning"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.2,<3"
scipy = ">=1.16.1,<2"
scikit-learn = ">=1.7.1,<2"
ipykernel = ">=6.30.1,<7"
matplotlib = ">=3.10.5,<4"
seaborn = ">=0.13.2,<0.14"
